import type { Metadata } from "next";
import { MainLayout } from "@/components/layouts/MainLayout";
import { TranslationProvider } from "@/hooks/useLanguage";
import { mainFont } from "@/assets/fonts";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const RootLayout = ({ children }: { children: React.ReactNode }) => {
  return (
    <TranslationProvider>
      <html lang="en">
        <body className={`${mainFont.className} max-w-full w-screen`}>
          <MainLayout>{children}</MainLayout>
        </body>
      </html>
    </TranslationProvider>
  );
};

export default RootLayout;
